### PR TITLE
:art: Create dependabot automerge action

### PR DESCRIPTION
**Pull request by flaxel**
### Type of Change

- [ ] Bugfix
- [x] Enhancement / new feature
- [ ] Refactoring
- [ ] Documentation

### Description

- create dependabot auto-merge action
- tested in own testing environment (see comment)
- ⚠️ using real version in autodev action project

### Checklist

- [x] Add relevant labels (for example type of change or patch/minor/major)
- [x] Make sure not to introduce some mistakes
- [x] Update documentation
- [x] Review the [Contributing Guideline](../blob/main/CONTRIBUTING.md) and sign CLA
- [ ] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by flaxel** [comment]
I tested the workflow in my [own testing environment](https://github.com/flaxel/test-gha/pull/65):

Bildschirmfoto 2023-11-01 um 13 55 03

**Comment by 0x46616c6b** [comment]
> I tested the workflow in my [own testing environment](https://github.com/flaxel/test-gha/pull/65):
> 
> Bildschirmfoto 2023-11-01 um 13 55 03

But your checks in the repository are not required. I had the experience when you have required checks that it can fail.

**Comment by flaxel** [comment]
I had a required step and it works perfectly. 🙌 The codeowner issue can be solved in each repository explicitly with an adaption of the CODEOWNERS file. But I would keep this configuration in the specific repository. 🎉

**Review by timdittler — APPROVED** [review]
I agree that we can iterate on it if it is in a basic working state, which it seems to be. I would like see a bit of additional docs (e.g. CODEOWNERS). Maybe add a verbal hint, that this workflow will be called by the `on: pull_request` workflow, thereby on dependabot PRs.

**Pull request merged**
